create table "public"."serp_links" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "update_at" timestamp with time zone not null default now(),
    "link" text not null,
    "title" text not null,
    "description" text,
    "global_rank" bigint,
    "serp_request_id" text
);


create table "public"."serp_search" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "search_engine" text not null default 'google'::text,
    "query" text not null,
    "request_id" text not null,
    "is_tracked" boolean not null default false
);


create table "public"."yt_comments" (
    "content" text not null,
    "replies" text[] not null,
    "video_id" text,
    "id" text not null
);


create table "public"."yt_videos" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "url" text,
    "title" text,
    "likes" bigint,
    "views" bigint,
    "date_posted" date,
    "description" text,
    "num_comments" bigint,
    "preview_image" text,
    "youtuber_id" text,
    "transcript" text,
    "ai_summary" text,
    "ai_topics" text[],
    "comments_sentiment" text,
    "comments_sentiment_score" real,
    "comments_sentiment_explanation" text,
    "comments_topics" text[]
);


alter table "public"."scrape_jobs" add column "dataset_id" text;

alter table "public"."yt_channels" add column "is_tracked" boolean not null default false;

CREATE UNIQUE INDEX serp_links_pkey ON public.serp_links USING btree (id);

CREATE UNIQUE INDEX serp_search_pkey ON public.serp_search USING btree (request_id);

CREATE UNIQUE INDEX yt_comments_pkey ON public.yt_comments USING btree (id);

CREATE UNIQUE INDEX yt_videos_pkey ON public.yt_videos USING btree (id);

alter table "public"."serp_links" add constraint "serp_links_pkey" PRIMARY KEY using index "serp_links_pkey";

alter table "public"."serp_search" add constraint "serp_search_pkey" PRIMARY KEY using index "serp_search_pkey";

alter table "public"."yt_comments" add constraint "yt_comments_pkey" PRIMARY KEY using index "yt_comments_pkey";

alter table "public"."yt_videos" add constraint "yt_videos_pkey" PRIMARY KEY using index "yt_videos_pkey";

alter table "public"."serp_links" add constraint "serp_links_serp_request_id_fkey" FOREIGN KEY (serp_request_id) REFERENCES serp_search(request_id) not valid;

alter table "public"."serp_links" validate constraint "serp_links_serp_request_id_fkey";

alter table "public"."yt_comments" add constraint "yt_comments_video_id_fkey" FOREIGN KEY (video_id) REFERENCES yt_videos(id) not valid;

alter table "public"."yt_comments" validate constraint "yt_comments_video_id_fkey";

alter table "public"."yt_videos" add constraint "yt_videos_youtuber_id_fkey" FOREIGN KEY (youtuber_id) REFERENCES yt_channels(id) not valid;

alter table "public"."yt_videos" validate constraint "yt_videos_youtuber_id_fkey";

grant delete on table "public"."serp_links" to "anon";

grant insert on table "public"."serp_links" to "anon";

grant references on table "public"."serp_links" to "anon";

grant select on table "public"."serp_links" to "anon";

grant trigger on table "public"."serp_links" to "anon";

grant truncate on table "public"."serp_links" to "anon";

grant update on table "public"."serp_links" to "anon";

grant delete on table "public"."serp_links" to "authenticated";

grant insert on table "public"."serp_links" to "authenticated";

grant references on table "public"."serp_links" to "authenticated";

grant select on table "public"."serp_links" to "authenticated";

grant trigger on table "public"."serp_links" to "authenticated";

grant truncate on table "public"."serp_links" to "authenticated";

grant update on table "public"."serp_links" to "authenticated";

grant delete on table "public"."serp_links" to "service_role";

grant insert on table "public"."serp_links" to "service_role";

grant references on table "public"."serp_links" to "service_role";

grant select on table "public"."serp_links" to "service_role";

grant trigger on table "public"."serp_links" to "service_role";

grant truncate on table "public"."serp_links" to "service_role";

grant update on table "public"."serp_links" to "service_role";

grant delete on table "public"."serp_search" to "anon";

grant insert on table "public"."serp_search" to "anon";

grant references on table "public"."serp_search" to "anon";

grant select on table "public"."serp_search" to "anon";

grant trigger on table "public"."serp_search" to "anon";

grant truncate on table "public"."serp_search" to "anon";

grant update on table "public"."serp_search" to "anon";

grant delete on table "public"."serp_search" to "authenticated";

grant insert on table "public"."serp_search" to "authenticated";

grant references on table "public"."serp_search" to "authenticated";

grant select on table "public"."serp_search" to "authenticated";

grant trigger on table "public"."serp_search" to "authenticated";

grant truncate on table "public"."serp_search" to "authenticated";

grant update on table "public"."serp_search" to "authenticated";

grant delete on table "public"."serp_search" to "service_role";

grant insert on table "public"."serp_search" to "service_role";

grant references on table "public"."serp_search" to "service_role";

grant select on table "public"."serp_search" to "service_role";

grant trigger on table "public"."serp_search" to "service_role";

grant truncate on table "public"."serp_search" to "service_role";

grant update on table "public"."serp_search" to "service_role";

grant delete on table "public"."yt_comments" to "anon";

grant insert on table "public"."yt_comments" to "anon";

grant references on table "public"."yt_comments" to "anon";

grant select on table "public"."yt_comments" to "anon";

grant trigger on table "public"."yt_comments" to "anon";

grant truncate on table "public"."yt_comments" to "anon";

grant update on table "public"."yt_comments" to "anon";

grant delete on table "public"."yt_comments" to "authenticated";

grant insert on table "public"."yt_comments" to "authenticated";

grant references on table "public"."yt_comments" to "authenticated";

grant select on table "public"."yt_comments" to "authenticated";

grant trigger on table "public"."yt_comments" to "authenticated";

grant truncate on table "public"."yt_comments" to "authenticated";

grant update on table "public"."yt_comments" to "authenticated";

grant delete on table "public"."yt_comments" to "service_role";

grant insert on table "public"."yt_comments" to "service_role";

grant references on table "public"."yt_comments" to "service_role";

grant select on table "public"."yt_comments" to "service_role";

grant trigger on table "public"."yt_comments" to "service_role";

grant truncate on table "public"."yt_comments" to "service_role";

grant update on table "public"."yt_comments" to "service_role";

grant delete on table "public"."yt_videos" to "anon";

grant insert on table "public"."yt_videos" to "anon";

grant references on table "public"."yt_videos" to "anon";

grant select on table "public"."yt_videos" to "anon";

grant trigger on table "public"."yt_videos" to "anon";

grant truncate on table "public"."yt_videos" to "anon";

grant update on table "public"."yt_videos" to "anon";

grant delete on table "public"."yt_videos" to "authenticated";

grant insert on table "public"."yt_videos" to "authenticated";

grant references on table "public"."yt_videos" to "authenticated";

grant select on table "public"."yt_videos" to "authenticated";

grant trigger on table "public"."yt_videos" to "authenticated";

grant truncate on table "public"."yt_videos" to "authenticated";

grant update on table "public"."yt_videos" to "authenticated";

grant delete on table "public"."yt_videos" to "service_role";

grant insert on table "public"."yt_videos" to "service_role";

grant references on table "public"."yt_videos" to "service_role";

grant select on table "public"."yt_videos" to "service_role";

grant trigger on table "public"."yt_videos" to "service_role";

grant truncate on table "public"."yt_videos" to "service_role";

grant update on table "public"."yt_videos" to "service_role";

CREATE TRIGGER "TriggerAIAnalysis" AFTER INSERT ON public.yt_videos FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://otfegrqsmgprrobcfhch.supabase.co/functions/v1/ai_video_analysis', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZmVncnFzbWdwcnJvYmNmaGNoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzEyNjA5NSwiZXhwIjoyMDUyNzAyMDk1fQ.7y26f2mc02g7Z8NsWjsiRQa8auUnUM7XZIjQlcpWwiQ"}', '{}', '5000');


